git_repository(
    name = "io_bazel_rules_kotlin",
    remote = "https://github.com/bazelbuild/rules_kotlin.git",
    commit = "92a3cfc08f7f7551ddc1bf92cdc6defb1080b5ff",
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()

maven_jar(
    name = "assertj3_11_1",
    artifact = "org.assertj:assertj-core:3.11.1",
)

maven_jar(
    name = "junit4_12",
    artifact = "junit:junit:jar:4.12",
)